### ISSUE TITLE
Support multiple files with same file name

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/update-creator-tool#26]
Let's say we have two files below to be modified via the WUM update. 

  - repository/deployment/server/jaggeryapps/publisher/site/themes/wso2/templates/item-manage/template.jag
  - repository/deployment/server/jaggeryapps/publisher/site/themes/wso2/templates/life-cycles/template.jag

Update creator tool requires one folder as an input that containing all the modified files in the root level. But here, both file names are template.jag and we can't basically copy them into the same folder as they overwrite each other.

**Comment by thusithathilina** [comment]
@malinthaprasan Can you try just copy the item-manage and life-cycles directories?

**Comment by kasunsiyambalapitiya** [comment]
This can be achieved via copying the updated files with their relative paths to the resource directory (used for creating the update) as follows,

- `repository/deployment/server/jaggeryapps/publisher/site/themes/wso2/templates/item-manage/template.jag`

- `repository/deployment/server/jaggeryapps/publisher/site/themes/wso2/templates/life-cycles/template.jag`

![screenshot from 2018-09-13 10-55-07](https://user-images.githubusercontent.com/16388948/45468685-8cef8780-b743-11e8-9f65-8020566c57dc.png)

**Comment by nishadi** [comment]
Closing as of the above comment.
